# Generated by Django 3.2.25 on 2024-12-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonebook',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
